run:session8_dfsbfs.o session8_dfsbfs_client.c
	gcc session8_dfsbfs.o session8_dfsbfs_client.c -o run
session8_dfsbfs.o:session8_dfsbfs.c session8_dfsbfs.h
	gcc session8_dfsbfs.c -c
session8_dfsbfs_client.o:session8_dfsbfs_client.c session8_dfsbfs.h
	gcc session8_dfsbfs_client.c -c
